### ISSUE TITLE
Apparently 1.0.4 broke the ability to auto-lock my screen

### ISSUE THREAD

**Issue by fckpepo** [SniperGER/ReScale2#2]
I installed it, upscaled it to iPhone 12 Pro Max resolution (i'm using an 11 Pro), and then suddenly my screen stopped auto-locking. I tried to remove the tweak and erase its preferences, but this happens even into unjailbroken state.

**Comment by SniperGER** [comment]
Looks like I forgot to reenable lockscreen timeout in unexpected situations. I'm probably going to rework this a little bit anyways.

In the meantime, could you please test this package and see if it improves your situation? Unfortunately, I had to put the .deb in a .zip for GitHub to let me upload it.
[tf.festival.rescale2_1.0.4-1_iphoneos-arm.deb.zip](https://github.com/SniperGER/ReScale2/files/6389737/tf.festival.rescale2_1.0.4-1_iphoneos-arm.deb.zip)

**Comment by fckpepo** [comment]
No problems about the zip ^^ 
Actually, this deb works in a peculiar way. If I set the auto-lock time to 1 minute, it dims the screen when around 40s has passed, and locks at the completion of 1 minute. If the time is other than 1 minute (LPM's 30s, normal 30s, 2 minutes, etc), the iPhone stays unlocked with no dims.

**Comment by fckpepo** [comment]
I used this package you sent me here to do the procedure you've listed down into the "design notes" of the tweak (If you have set a higher resolution and your device is rebooted, it is recommended to rejailbreak with tweaks disabled ("Safe Mode" in checkra1n) and disable Re:Scale 2 using iCleaner before rejailbreaking again with tweaks enabled.), and it worked as far as I tested ^^ thank you so much! 

I still hope you can figure it out, so I can re-install your tweak, for real! Thank you for your time and effort <3

**Comment by SniperGER** [comment]
Hey there, I've got another build for you to test, which uses a different approach so that disabling the lockscreen timeout is actually only applied when being jailbroken and not in Safe Mode. You may not see any differences, and if that's the case, that's actually good. The first build still could fail temporarily when the device enters Safe Mode while the 30 second reset dialog is still shown.

If everything works out, this will be the release build.
[tf.festival.rescale2_1.0.4-1_iphoneos-arm.deb.zip](https://github.com/SniperGER/ReScale2/files/6396703/tf.festival.rescale2_1.0.4-1_iphoneos-arm.deb.zip)
